import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import App from "./_app";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";

export default function Home() {
  const { isLoading, error, data } = useQuery({
    queryKey: ["repoData"],
    queryFn: async () => {
      const res = await axios.get(
        "https://63b8599a3329392049da66ac.mockapi.io/api/v1/hotels"
      );
      console.log({ res });
      return res.data;
    },
  });

  console.log({ data });

  return (
    <>
      <Head>
        <title>Hotel & CO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* Setting the the header of the App */}
        <div className={styles.heading}>
          <div className={styles.headingWrapper}>
            {[...new Array(12)].map((e, i) => (
              <div className={styles.headerContainer} key={i}>
                <Header />
              </div>
            ))}
          </div>
        </div>
        <div className={styles.mainWrapper}>
          {[...new Array(20)].map((e, i: number) => (
            <Card key={i} />
          ))}
          {/* {data?.map((e, i: number) => (
            <Card key={i} />
          ))} */}
        </div>
        <Footer />
      </main>
    </>
  );
}
