import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import App from "./_app";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel & CO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* Setting the the header of the App */}
        <div className={styles.heading}>
          <div className={styles.headingWrapper}>
            {[...new Array(12)].map((e, i) => (
              <div className={styles.headerContainer} key={i}>
                <Header />
              </div>
            ))}
          </div>
        </div>
        <div className={styles.mainWrapper}>
          {[...new Array(34)].map((e, i) => (
            <Card key={i} />
          ))}
        </div>
        <Footer />
      </main>
    </>
  );
}
